---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 8-demo-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: 8-demo
  url: https://github.com/EmrhT/bb-app-source
