---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-security-kustomize-git-sealed-secrets
  namespace: flux-system
spec:
  interval: 30s
  path: ./bitnami-sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-source-git
